#!/bin/bash
#SBATCH -p gpu
#SBATCH --gres=gpu:2
#SBATCH -o %x_%u_%j.out # File to which STDOUT will be written
#SBATCH -e %x_%u_%j.err # File to which STDERR will be written
#SBATCH -t 0-04:00

python -c "import torch; print(f'versio {torch.__version__} <-> {torch.version.cuda}');print(f'GPUs: {torch.cuda.device_count()}')"